=== ConsumerDataStandardsAustralia/standards-testing/tools/testdata-cli/src/schema/cdr-test-data-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "cdr-test-data-schema",
	"title": "Consumer Data Right Test Data JSON Schema",
	"description": "A JSON schema for defining test data files that can be used to seed a mock, or test, implementation of a Data Holder for the Consumer Data Right",
	"type": "object",
	"required": [
		"fileVersion",
		"standardsVersion",
		"title"
	],
	"additionalProperties": false,
	"properties": {
		"fileVersion": {
			"type": "string",
			"description": "The version of the file formatted using semver (without extensions)",
			"pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
		},
		"standardsVersion": {
			"type": "string",
			"description": "The version of the CDR standards that these tests are validated for.  For formatted using semver (without extensions)",
			"pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
		},
		"title": {
			"type": "string",
			"description": "A short title of the test data file"
		},
		"description": {
			"type": "string",
			"description": "An optional description of the test data file to identify its purpose"
		},
		"holders": {
      "$ref": "#/$defs/holders"
		},
		"clientCache": {
      "type": "array",
      "description": "A cache of previously registered clients",
      "items": {
        "$ref": "#/$defs/client"
      }
		},
		"registerCache": {
      "type": "array",
      "description": "A cache of previously loaded recipients from the CDR Register",
      "items": {
        "$ref": "#/$defs/recipient"
      }
		}
	},
	"$defs": {
    "holders": {
      "type": "array",
      "description": "An array of holders and their data",
      "items": {
        "$ref": "#/$defs/holderWrapper"
      }
    },
    "holderWrapper": {
      "type": "object",
			"description": "A wrapper for a single holder to contain all of the data related to the holder",
      "additionalProperties": false,
      "required": [
        "holderId",
        "holder"
      ],
      "properties": {
        "holderId": {
          "type": "string",
          "description": "The unique internal ID of the holder"
        },
        "holder": {
          "$ref": "#/$defs/holder"
        }
      }
    },
		"holder": {
			"type": "object",
			"description": "Data for a single data holder",
			"additionalProperties": false,
      "required": [
        "unauthenticated",
        "authenticated"
      ],
			"properties": {
        "unauthenticated": {
          "$ref": "#/$defs/unauthenticated"
        },
				"authenticated": {
          "$ref": "#/$defs/authenticated"
				}
      }
    },
    "unauthenticated": {
			"type": "object",
			"description": "Unauthenticated data for a single data holder",
			"additionalProperties": false,
			"properties": {
        "banking": {
          "type": "object",
					"description": "Unauthenticated banking data",
					"additionalProperties": false,
          "properties": {
            "products": {
              "type": "array",
							"description": "An array of banking products",
              "items": {
                "$ref": "#/$defs/bankProduct"
              }
            }
          }
        },
        "energy": {
          "type": "object",
					"description": "Unauthenticated energy data",
					"additionalProperties": false,
          "properties": {
            "plans": {
              "type": "array",
							"description": "An array of energy plans",
              "items": {
                "$ref": "#/$defs/energyPlan"
              }
            }
          }
        },
        "admin": {
          "type": "object",
					"description": "Current system status",
					"additionalProperties": false,
          "properties": {
            "status": {
              "$ref": "#/$defs/adminStatus"
            },
            "outages": {
              "type": "array",
							"description": "An array of planned outages",
              "items": {
                "$ref": "#/$defs/adminOutage"
              }
            }
          }
        }
			}
    },
		"authenticated": {
			"type": "object",
			"description": "Authenticated data for a single data holder",
			"additionalProperties": false,
			"properties": {
				"customers": {
					"type": "array",
					"description": "An array of customers and their data",
          "items": {
            "$ref": "#/$defs/customerWrapper"
          }
				}
			}
		},
		"client": {
			"type": "object",
			"description": "A previously registered client aligned to the current version of the data standards"
		},
		"recipient": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/register/RegisterDataRecipient.json"
		},
    "bankProduct": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/banking/BankingProductDetailV4"
		},
    "energyPlan": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/energy/EnergyPlanDetail.json"
		},
    "adminStatus": {
			"type": "object",
			"description": "A status object for the holder"
		},
    "adminOutage": {
			"type": "object",
			"description": "A planned outage object for the holder"
		},
    "customerWrapper": {
      "type": "object",
			"description": "A wrapper for a single customer to contain all of the data related to the customer",
      "additionalProperties": false,
      "required": [
        "customerId",
        "customer"
      ],
      "properties": {
        "customerId": {
          "type": "string",
          "description": "The unique internal ID of the customer"
        },
        "customer": {
          "$ref": "#/$defs/customer"
        },
        "banking": {
          "type": "object",
    			"description": "Banking data for this customer",
          "properties": {
            "accounts": {
              "type": "array",
              "description": "An array of accounts and their data",
              "items": {
                "$ref": "#/$defs/bankAccountWrapper"
              }
            },
            "directDebits": {
              "type": "array",
              "description": "An array of direct debit authorisations",
              "items": {
                "$ref": "#/$defs/bankDirectDebit"
              }
            },
            "payees": {
              "type": "array",
              "description": "An array of payees",
              "items": {
                "$ref": "#/$defs/bankPayee"
              }
            },
            "payments": {
              "type": "array",
              "description": "An array of payment schedules",
              "items": {
                "$ref": "#/$defs/bankPaymentSchedule"
              }
            }
          }
        },
        "energy": {
          "type": "object",
    			"description": "Energy data for this customer",
          "properties": {
            "accounts": {
              "type": "array",
              "description": "An array of accounts and their data",
              "items": {
                "$ref": "#/$defs/energyAccountWrapper"
              }
            },
            "servicePoints": {
              "type": "array",
              "description": "An array of service points and their data",
              "items": {
                "$ref": "#/$defs/energyServicePointWrapper"
              }
            }
          }
        }
      }
    },
    "customer": {
      "type": "object",
			"description": "A customer object aligned to the current version of the data standards"
    },
    "bankDirectDebit": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/banking/BankingDirectDebit.json"
    },
    "bankPayee": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/banking/BankingPayeeDetailV2.json"
    },
    "bankPaymentSchedule": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/banking/BankingScheduledPayment.json"
    },
    "bankAccountWrapper": {
      "type": "object",
			"description": "A wrapper for a single bank account to contain all of the data related to the account",
      "additionalProperties": false,
      "required": [
        "account"
      ],
      "properties": {
        "account": {
          "$ref": "#/$defs/bankAccount"
        },
        "balance": {
          "$ref": "#/$defs/bankAccountBalance"
        },
        "transactions": {
          "type": "array",
          "description": "An array of transactions for the account",
          "items": {
            "$ref": "#/$defs/bankTransaction"
          }
        }
      }
    },
    "bankAccount": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/banking/BankingAccountDetailV2.json"
    },
    "bankAccountBalance": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/banking/BankingBalance.json"
    },
    "bankTransaction": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/banking/BankingTransactionDetail.json"
    },
    "energyAccountWrapper": {
      "type": "object",
			"description": "A wrapper for a single eenrgy account to contain all of the data related to the account",
      "additionalProperties": false,
      "required": [
        "account"
      ],
      "properties": {
        "account": {
          "$ref": "#/$defs/energyAccount"
        },
        "balance": {
          "$ref": "#/$defs/energyAccountBalance"
        },
        "paymentSchedule": {
          "type": "array",
          "description": "An array of agreed payment schedules",
          "items": {
            "$ref": "#/$defs/energyPaymentSchedule"
          }
        },
        "invoices": {
          "type": "array",
          "description": "An array of invoices for the account",
          "items": {
            "$ref": "#/$defs/energyInvoice"
          }
        },
        "transactions": {
          "type": "array",
          "description": "An array of transactions for the account",
          "items": {
            "$ref": "#/$defs/energyTransaction"
          }
        },
        "concessions": {
          "type": "array",
          "description": "An array of concessions for the account",
          "items": {
            "$ref": "#/$defs/energyConcession"
          }
        }
      }
    },
    "energyAccount": {
      "%ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/energy/EnergyAccountDetailV2.json"
    },
    "energyAccountBalance": {
      "type": "object",
			"description": "Distributed energy resources for an energy account aligned to the current version of the data standards"
    },
    "energyPaymentSchedule": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/energy/EnergyPaymentSchedule.json"
      },
    "energyInvoice": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/energy/EnergyInvoice.json"
    },
    "energyTransaction": {
      "type": "object",
			"description": "An energy transaction aligned to the current version of the data standards"
    },
    "energyConcession": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/energy/EnergyConcession.json"
    },
    "energyServicePointWrapper": {
      "type": "object",
			"description": "An energy for a single service point (metering site) to contain all of the data related to the service point",
      "additionalProperties": false,
      "required": [
        "account",
        "balance"
      ],
      "properties": {
        "servicePoint": {
          "$ref": "#/$defs/energyServicePoint"
        },
        "der": {
          "$ref": "#/$defs/energyDerData"
        },
        "usage": {
          "type": "array",
          "description": "An array of reads for the service point",
          "items": {
            "$ref": "#/$defs/energyUsageRead"
          }
        }
      }
    },
    "energyServicePoint": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/energy/EnergyServicePointDetail.json"
          },
    "energyDerData": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/energy/EnergyDerRecord.json"
    },
    "energyUsageRead": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.20.0/schemas/energy/EnergyUsageRead.json"
     }
	}
}

=== ConsumerDataStandardsAustralia/standards-testing/tools/testdata-cli/samples/output/my-created-service-point-data.json
{
  "fileVersion": "1.0.0",
  "standardsVersion": "1.18.0",
  "title": "Automatically generated data file",
  "description": "Test data generated by the CDR Test Data CLI",
  "holders": [
    {
      "holderId": "801893278",
      "holder": {
        "unauthenticated": {},
        "authenticated": {
          "customers": [
            {
              "customerId": "121645127",
              "customer": {
                "customerUType": "organisation",
                "organisation": {
                  "physicalAddresses": [
                    {
                      "purpose": "REGISTERED",
                      "addressUType": "simple",
                      "simple": {
                        "mailingName": "Windler, Wolf and Patel",
                        "localityName": "Ebertmouth",
                        "addressLine1": "Fay Way",
                        "postcode": "7678",
                        "city": "Flower Mound",
                        "state": "Western Australia",
                        "country": "AUS"
                      }
                    },
                    {
                      "purpose": "MAIL",
                      "addressUType": "paf",
                      "paf": {
                        "localityName": "Turner and Sons",
                        "postcode": "6808",
                        "state": "Australian Capital Territory",
                        "postalDeliveryType": "LOCKED_BAG",
                        "postalDeliveryNumber": 28178337,
                        "flatUnitType": "UNIT",
                        "flatUnitNumber": "46"
                      }
                    },
                    {
                      "purpose": "OTHER",
                      "addressUType": "paf",
                      "paf": {
                        "localityName": "Leannon Brothers",
                        "postcode": "2032",
                        "state": "Western Australia",
                        "postalDeliveryType": "CARE_PO",
                        "postalDeliveryNumber": 28841385,
                        "postalDeliveryNumberSuffix": "STS",
                        "postalDeliveryNumberPrefix": "APT",
                        "thoroughfareNumber1": 8196,
                        "thoroughfareNumber1Suffix": "HWY",
                        "thoroughfareNumber2": 8202,
                        "thoroughfareNumber2Suffix": "HWY",
                        "flatUnitType": "UNIT",
                        "flatUnitNumber": "48",
                        "floorLevelNumber": "43",
                        "buildingName1": "Reception area"
                      }
                    }
                  ],
                  "agentRole": "Unspecified",
                  "businessName": "Parker, Gutmann and Stokes",
                  "organisationType": "COMPANY",
                  "agentLastName": "Cruickshank",
                  "industryCode": "556913",
                  "industryCodeVersion": "ANZSIC_1292.0_2006_V2.0",
                  "shortName": "Short Name",
                  "registeredCountry": "ARG",
                  "abn": "586-356-697",
                  "acn": "928-737-705"
                }
              },
              "energy": {
                "servicePoints": [
                  {
                    "servicePoint": {
                      "jurisdictionCode": "QLD",
                      "lastUpdateDateTime": "2023-01-12T01:38:58.409Z",
                      "nationalMeteringId": "6239077048",
                      "servicePointClassification": "LARGE",
                      "servicePointId": "b319c2fb-19b3-4863-a46b-9e1ae1284f53",
                      "servicePointStatus": "ACTIVE",
                      "validFromDate": "2022-07-12T00:00:00.000Z",
                      "distributionLossFactor": {
                        "code": "ABCFR",
                        "description": "Mandatory dscription for distribution loss factor",
                        "lossValue": "15.36"
                      },
                      "location": {
                        "addressUType": "paf",
                        "paf": {
                          "localityName": "Stark - Wright",
                          "postcode": "0056",
                          "state": "Western Australia",
                          "postalDeliveryType": "GPO_BOX",
                          "postalDeliveryNumber": 27610750,
                          "postalDeliveryNumberSuffix": "STS",
                          "flatUnitNumber": "2",
                          "buildingName1": "Reception area"
                        }
                      },
                      "relatedParticipants": [
                        {
                          "party": "Waters, Dare and Jacobs",
                          "role": "LNSP"
                        }
                      ],
                      "consumerProfile": {
                        "classification": "BUSINESS",
                        "threshold": "MEDIUM"
                      },
                      "meters": [
                        {
                          "meterId": "506955295",
                          "specifications": {
                            "installationType": "COMMS4",
                            "status": "DE_ENERGISED"
                          }
                        },
                        {
                          "meterId": "597832599",
                          "specifications": {
                            "installationType": "COMMS2",
                            "status": "DE_ENERGISED"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "servicePoint": {
                      "jurisdictionCode": "QLD",
                      "lastUpdateDateTime": "2022-03-10T12:36:47.689Z",
                      "nationalMeteringId": "8043127465",
                      "servicePointClassification": "GENERATOR",
                      "servicePointId": "b35dd785-354c-419e-9e3c-46a1d1bf0afe",
                      "servicePointStatus": "ACTIVE",
                      "validFromDate": "2021-12-15T00:00:00.000Z",
                      "distributionLossFactor": {
                        "code": "ABCFR",
                        "description": "Mandatory dscription for distribution loss factor",
                        "lossValue": "19.60"
                      },
                      "location": {
                        "addressUType": "paf",
                        "paf": {
                          "localityName": "Ricardo Klein",
                          "postcode": "0936",
                          "state": "Queensland",
                          "thoroughfareNumber1": 4942,
                          "thoroughfareNumber1Suffix": "HWY",
                          "thoroughfareNumber2": 4943,
                          "thoroughfareNumber2Suffix": "HWY",
                          "floorLevelNumber": "19",
                          "streetName": "Georgia Parkway",
                          "streetType": "ROAD"
                        }
                      },
                      "relatedParticipants": [
                        {
                          "party": "Mann - Nicolas",
                          "role": "FRMP"
                        }
                      ],
                      "consumerProfile": {
                        "classification": "BUSINESS",
                        "threshold": "MEDIUM"
                      },
                      "meters": [
                        {
                          "meterId": "124645979",
                          "specifications": {
                            "installationType": "MRAM",
                            "status": "EXTINCT"
                          }
                        },
                        {
                          "meterId": "475249669",
                          "specifications": {
                            "installationType": "MRIM",
                            "status": "EXTINCT"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "servicePoint": {
                      "jurisdictionCode": "ALL",
                      "lastUpdateDateTime": "2021-05-13T18:25:48.177Z",
                      "nationalMeteringId": "2311570361",
                      "servicePointClassification": "SMALL",
                      "servicePointId": "00c326ec-4f83-4db3-b3aa-f7cf8df39e1b",
                      "servicePointStatus": "EXTINCT",
                      "validFromDate": "2020-07-13T00:00:00.000Z",
                      "distributionLossFactor": {
                        "code": "ABCFR",
                        "description": "Mandatory dscription for distribution loss factor",
                        "lossValue": "19.25"
                      },
                      "location": {
                        "addressUType": "simple",
                        "simple": {
                          "mailingName": "Anderson, Barton and Hickle",
                          "localityName": "Cameronboro",
                          "addressLine1": "Declan Pass",
                          "postcode": "4420",
                          "city": "Mount Pleasant",
                          "state": "New South Wales",
                          "country": "AUS",
                          "addressLine2": "Apt. 512"
                        }
                      },
                      "relatedParticipants": [
                        {
                          "party": "Johns Pty Ltd",
                          "role": "DRSP"
                        }
                      ],
                      "consumerProfile": {
                        "classification": "BUSINESS",
                        "threshold": "HIGH"
                      },
