=== ConsumerDataStandardsAustralia/standards-testing/schema/cdr-test-doc-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://cds.gov.au/cdr-test-schema.0.0.4.json",
    "title": "Consumer Data Right Test Case JSON Schema",
    "description": "A JSON schema for defining test cases to be used to document test cases for compliance with the Consumer Data Right data standards",
    "type": "object",
    "required": [
        "fileVersion",
        "standardsVersion",
        "title"
    ],
    "additionalProperties": false,
    "properties": {
        "fileVersion": {
            "type": "string",
            "description": "The version of the file formatted using semver (without extensions)",
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
        },
        "standardsVersion": {
            "type": "string",
            "description": "The version of the CDR standards that these tests are validated for.  For formatted using semver (without extensions)",
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
        },
        "title": {
            "type": "string",
            "description": "A short title of the test file"
        },
        "description": {
            "type": "string",
            "description": "An optional description of the test case file to identify its purpose"
        },
        "githubRepoUrl": {
            "type": "string",
            "description": "An optional url for the public GitHub repository"
        },
        "changeLogUrl": {
            "type": "string",
            "description": "An optional url for the change log"
        },
        "assertions": {
            "type": "object",
            "description": "A set of assertions named with the ID of the assertion in format 'A.XXX.000' where XXX is category and 000 is the unique identifier",
            "additionalProperties": false,
            "patternProperties": {
                "^A\\.[A-Z]{3}\\.[0-9]{3}$": {
                    "$ref": "#/$defs/assertion"
                }
            }
        },
        "testCases": {
            "type": "object",
            "description": "A set of test cases named with the ID of the test case in format 'T.XXX.000' where XXX is category and 000 is the unique identifier",
            "additionalProperties": false,
            "patternProperties": {
                "^T\\.[A-Z]{3}\\.[0-9]{3}$": {
                    "$ref": "#/$defs/testCase"
                }
            }
        },
        "scenarios": {
            "type": "object",
            "description": "A set of test scenarios that link together multiple test cases in sequence. Named with the ID of the scenarion in format 'S.XXX.000' where XXX is category and 000 is the unique identifier",
            "additionalProperties": false,
            "patternProperties": {
                "^S\\.[A-Z]{3}\\.[0-9]{3}$": {
                    "$ref": "#/$defs/scenario"
                }
            }
        },
        "suites": {
            "type": "object",
            "description": "A suite of test scenarios used to bundle all of the tests for a specific domain.  Each suite is named using the format 'SUITE.TEXT' where TEXT is any name using a sequence of letters and digits that describes the suite",
            "additionalProperties": false,
            "patternProperties": {
                "^SUITE\\.[a-zA-Z0-9]+$": {
                    "$ref": "#/$defs/suite"
                }
            }
        }
    },
    "$defs": {
        "assertion": {
            "type": "object",
            "description": "A single atomic test assertion",
            "additionalProperties": false,
            "required": [
                "id",
                "title",
                "given",
                "when",
                "then"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "description": "A Unique assertion identifier"
                },
                "title": {
                    "type": "string",
                    "description": "A short title of the assertion"
                },
                "description": {
                    "type": "string",
                    "description": "An optional description of the assertion giving additional information"
                },
                "references": {
                    "type": "array",
                    "description": "An array of references for additional relevant information",
                    "items": {
                        "$ref": "#/$defs/reference"
                    }
                },
                "negative": {
                    "type": "boolean",
                    "description": "Indicates if this is a negative assertion.  False if absent",
                    "default": false
                },
                "severity": {
                    "type": "string",
                    "description": "The implication of this assertion failing on CDR compliance",
                    "enum": [
                        "FAIL",
                        "INFO",
                        "WARN"
                    ],
                    "default": "FAIL"
                },
                "given": {
                    "type": "array",
                    "description": "An array of 'given' statements describing the context of the assertion",
                    "items": {
                        "type": "string"
                    }
                },
                "when": {
                    "type": "array",
                    "description": "An array of 'given' statements describing the context"

                },
                "then": {
                    "$ref": "#/$defs/assertionPredicate"
                }
            }
        },
        "testCase": {

            "type": "object",
            "description": "A test case defined using Behaviour Driven Development principles",
            "additionalProperties": false,
            "required": [
                "id",
                "title",
                "steps"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "description": "A Unique test case identifier"
                },
                "title": {
                    "type": "string",
                    "description": "A short title of the test case"
                },
                "description": {
                    "type": "string",
                    "description": "An optional description of the test case giving additional information"
                },
                "references": {
                    "type": "array",
                    "description": "An array of references for additional relevant information",
                    "items": {
                        "$ref": "#/$defs/reference"
                    }
                },
                "negative": {
                    "type": "boolean",
                    "description": "Indicates if this is a negative test case.  False if absent",
                    "default": false
                },
                "purpose": {
                    "type": "string",
                    "description": "A description of the test case defined as a testable story in 'As A... I Want... Such That...' format"
                },
                "preConditions": {
                    "type": "array",
                    "description": "An array of conditions that must be met before the test case is executed",
                    "items": {
                        "type": "string"
                    }
                },
                "steps": {
                    "type": "array",
                    "description": "An array of steps to execute the test case",
                    "items": {
                        "$ref": "#/$defs/testCaseStep"
                    }
                },
                "assertions": {
                    "type": "array",
                    "description": "An array assertion identifiers associated with this test case",
                    "items": {
                        "type": "string",
                        "description": "The unique assertion identifier"
                    }
                }
            }
        },
        "scenario": {
            "type": "object",
            "description": "A test scenario made up of a sequence of test cases and additonal actions to prepare for the tests",
            "additionalProperties": false,
            "required": [
                "id",
                "title",
                "purpose",
                "sequence"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "description": "A Unique scenario identifier"
                },
                "title": {
                    "type": "string",
                    "description": "A short title of the scenario"
                },
                "description": {
                    "type": "string",
                    "description": "An optional description of the scenario giving additional information"
                },
                "references": {
                    "type": "array",
                    "description": "An array of references for additional relevant information",
                    "items": {
                        "$ref": "#/$defs/reference"
                    }
                },
                "purpose": {
                    "type": "string",
                    "description": "A description of the purpose of this test scenario indicating what the scenario is intended to test"
                },
                "sequence": {
                    "type": "array",
                    "description": "An sequence of actions to execute the test scenario",
                    "items": {
                        "$ref": "#/$defs/scenarioAction"
                    }
                }
            }
        },
        "suite": {
            "type": "object",
            "description": "A suite of test scenarios that are bundled to achieve a specific testing purpose",
            "additionalProperties": false,
            "required": [
                "id",
                "title",
                "purpose",
                "scenarios"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "description": "A Unique suite identifier"
                },
                "title": {
                    "type": "string",
                    "description": "A short title of the test suite"
                },
                "description": {
                    "type": "string",
                    "description": "An optional description of the suite giving additional information"
                },
                "references": {
                    "type": "array",
                    "description": "An array of references for additional relevant information",
                    "items": {
                        "$ref": "#/$defs/reference"
                    }
                },
                "purpose": {
                    "type": "string",
                    "description": "A description of the purpose of this suite indicating what the suite is intended to test"
                },
                "scenarios": {
                    "type": "array",
                    "description": "An array of scenarios (reference by scenario ID) included in the suite",
                    "items": {
                        "type": "string",
                        "pattern": "^S\\.[A-Z]{3}\\.[0-9]{3}$"
                    }
                }
            }

        },
        "reference": {
            "type": "object",
            "description": "A reference to additional information",
            "additionalProperties": false,
            "required": [
                "uri"
            ],
            "properties": {
                "alt": {
                    "type": "string",
                    "description": "Display name for the reference"
                },
                "uri": {
                    "type": "string",
                    "description": "Link to the reference",
                    "format": "uri"
                }
            }
        },
        "assertionPredicate": {
            "description": "A recursive combination of text based assertion statements combined using AND or OR operators",
            "oneOf": [{
                    "type": "string"
                },
                {
                    "type": "object",
                    "required": [
                        "and"
                    ],
                    "properties": {
                        "and": {
                            "type": "array",
                            "items": {
                                "$ref": "#/$defs/assertionPredicate"
                            }
                        }
                    }
                },
                {
                    "type": "object",
                    "required": [
                        "or"
                    ],
                    "properties": {
                        "or": {
                            "type": "array",
                            "items": {
                                "$ref": "#/$defs/assertionPredicate"
                            }
                        }
                    }
                }
            ]
        },
        "testCaseStep": {
            "description": "A single step in a test case",
            "oneOf": [{
                    "type": "object",
                    "description": "Wait for a period of time",
                    "required": [
                        "type",
                        "period"
                    ],
                    "properties": {
                        "type": {
                            "const": "WAIT"
                        },
                        "period": {
                            "type": "integer",
                            "description": "Number of seconds to wait",
                            "minimum": 1
                        }
                    }
                },
                {
                    "type": "object",
                    "description": "Delay until a condition has been met",
                    "required": [
                        "type",
                        "period"
                    ],
                    "properties": {
                        "type": {
                            "const": "UNTIL"
                        },
                        "condition": {
                            "type": "string",
                            "description": "The condition that must be met for the step to be complete"
                        }
                    }
                },
                {
                    "type": "object",
                    "description": "Perform an action",
                    "required": [
                        "type",
                        "action"
                    ],
                    "properties": {
                        "type": {
                            "const": "ACTION"
                        },
                        "action": {
                            "type": "string",
                            "description": "The action to be performed"
                        }
                    }
                },
                {
                    "type": "object",
                    "description": "Assert that a condition is true",
                    "required": [
                        "type",
                        "assertion"
                    ],
                    "properties": {
                        "type": {
                            "const": "ASSERTION"
                        },
                        "assertion": {
                            "$ref": "#/$defs/testCasePredicate"
                        }
                    }
                }
            ]
        },
        "testCasePredicate": {
            "description": "A recursive combination of pre-defined assertions combined using AND or OR operators",
            "oneOf": [{
                    "type": "string",
                    "pattern": "^A\\.[A-Z]{3}\\.[0-9]{3}$"
                },
                {
                    "type": "object",
                    "required": [
                        "and"
                    ],
                    "properties": {
                        "and": {
                            "type": "array",
                            "items": {
                                "$ref": "#/$defs/testCasePredicate"
                            }
                        }
                    }
                },
                {
                    "type": "object",
                    "required": [
                        "or"
                    ],
                    "properties": {
                        "or": {
                            "type": "array",
                            "items": {
                                "$ref": "#/$defs/testCasePredicate"
                            }
                        }
                    }
                }
            ]
        },
        "scenarioAction": {
            "description": "A single action the sequence of execution for a test scenario",
            "oneOf": [{
                    "type": "object",
                    "description": "Do some setup to prepare the test",
                    "required": [
                        "type",
                        "action"
                    ],
                    "properties": {
                        "type": {
                            "const": "SETUP"
                        },
                        "action": {
                            "type": "string",
                            "description": "The setup action to be performed"
                        }
                    }
                },
                {
                    "type": "object",
                    "description": "Perform a clean up action to reset state after the last test case",
                    "required": [
                        "type",
                        "action"
                    ],
                    "properties": {
                        "type": {
                            "const": "CLEANUP"
                        },
                        "action": {
                            "type": "string",
                            "description": "The clean up action to be performed"
                        }
                    }
                },
                {
                    "type": "object",
                    "description": "Execute a test case",
                    "required": [
                        "type",
                        "testCase"
                    ],
                    "properties": {
                        "type": {
                            "const": "TEST"
                        },
                        "testCase": {
                            "type": "string",
                            "description": "The ID of the test case to execute",
                            "pattern": "^T\\.[A-Z]{3}\\.[0-9]{3}$"
                        }
                    }
                }
            ]
        }
    }
}

=== ConsumerDataStandardsAustralia/standards-testing/tools/create-json-test-files/output-files/full-test-suite.json.json
{
  "fileVersion": "0.0.1",
  "standardsVersion": "0.0.1",
  "title": "Sample title",
  "description": "Sample description",
  "assertions": {
    "A.CPG.001": {
      "id": "A.CPG.001",
      "title": "Validate pagination - LinksPaginated ",
      "given": [
        "the page parameter is included in a GET request"
      ],
      "when": [
        "the page value is a number and page-size is [1,25,1000,null]"
      ],
      "then": {
        "and": [
          "the nominated <page number> is returned",
          " the response has a status of 200",
          " the \"first\" link has page=1",
          " the \"last\" link is greater than or equal to 1",
          " the \"self\" link has page=<page number>",
          " the \"prev\" link has page equal to 1 or <page number> - 1",
          " the \"prev\" link has page equal to \"last\" or <page number> + 1",
          " \"meta\"/\"totalPages\" is greater than or equal to <page number>",
          " \"meta\"/\"totalRecords\" is greater than or equal to <page number> * <page size>"
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#pagination"
        }
      ],
      "negative": false
    },
    "A.CPG.002": {
      "id": "A.CPG.002",
      "title": "Validate pagination - Invalid page size value",
      "given": [
        "the <page-size> parameter is specified in a GET request"
      ],
      "when": [
        "the value for <page-size> is outside the range [1..1000]",
        "OR the <page-size> is a not a positive integer"
      ],
      "then": {
        "and": [
          "the response has a status of 400",
          " the response body has ErrorListReponse object",
          " error code is \"Field/InvalidPageSize\""
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#error-codes"
        }
      ],
      "negative": false
    },
    "A.CPG.003": {
      "id": "A.CPG.003",
      "title": "Validate pagination - Non-numeric <page>",
      "given": [
        "the <page> parameter is included in a GET request"
      ],
      "when": [
        "the <page> is a not a positive integer"
      ],
      "then": {
        "and": [
          "the response has a status of 400",
          " the response body has ErrorListReponse object",
          " error code is \"Field/Invalid\""
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#error-codes"
        }
      ],
      "negative": false
    },
    "A.CPG.004": {
      "id": "A.CPG.004",
      "title": "Validate pagination - Max record limit exceeded",
      "given": [
        "the <page> parameter is included in a GET request"
      ],
      "when": [
        "the <page> value is greater than the number of pages available "
      ],
      "then": {
        "and": [
          "the response has a status of 422",
          " the response body has ErrorListReponse object",
          " the error code is \"Field/InvalidPage\""
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#error-codes"
        }
      ],
      "negative": false
    },
    "A.CPG.005": {
      "id": "A.CPG.005",
      "title": "Validate pagination - Non-numeric <page-size>",
      "given": [
        "the <page-size> parameter is included in a GET request"
      ],
      "when": [
        "the page size parameter value is not a positive integer (number)"
      ],
      "then": {
        "and": [
          "the response has a status of 400",
          " the response body has ErrorListReponse object",
          " error code is \"Field/Invalid\""
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#error-codes"
        }
      ],
      "negative": false
    },
    "A.CVN.001": {
      "id": "A.CVN.001",
      "title": "Validate version - valid version number [x-v]",
      "given": [
        "the <x-v> header is included in a get request"
      ],
      "when": [
        "the value for the <x-v> is a positive integer"
      ],
      "then": {
        "and": [
          "the response has a status of 200",
          " <x-v> is in the repsonse header",
          " <x-v> is a positive integer"
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#http-headers"
        }
      ],
      "negative": false
    },
    "A.CVN.002": {
      "id": "A.CVN.002",
      "title": "Validate version - invalid version value [x-v]",
      "given": [
        "the version parameter is included in a GET request"
      ],
      "when": [
        "the version value is not a valid number is [-1,0,1001]"
      ],
      "then": {
        "and": [
          "the response has a status of 400",
          " the response body has ErrorListReponse object",
          " error code is \"Field/Invalid\""
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#http-headers"
        }
      ],
      "negative": false
    },
    "A.CVN.003": {
      "id": "A.CVN.003",
      "title": "Validate version - validate [x-v] format",
      "given": [
        "the version parameter is included in a GET request"
      ],
      "when": [
        "the verison value is not a valid number is an alpha (e.g. \"foo\")"
      ],
      "then": {
        "and": [
          "the response has a status of 400",
          " the response body has ErrorListReponse object",
          " error code is \"Field/Invalid\""
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#http-headers"
        }
      ],
      "negative": false
    },
    "A.CVN.004": {
      "id": "A.CVN.004",
      "title": "Validate version - supported version without <x-v-min>",
      "given": [
        "the <x-v>  is included in a  request header",
        "AND <x-v-min> is NOT included"
      ],
      "when": [
        "the request version <x-v> is not supported"
      ],
      "then": {
        "and": [
          "the response has a status of 406",
          " the response body has ErrorListReponse object",
          " error code is \"Header/UnsupportedVersion\""
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#http-headers"
        }
      ],
      "negative": false
    },
    "A.CVN.005": {
      "id": "A.CVN.005",
      "title": "Validate version - supported version with <x-v-min>",
      "given": [
        "the <x-v>  is included in a  request header",
        "AND <x-v-min> is included"
      ],
      "when": [
        "no version between <x-v> and <x-min-v> is supported"
      ],
      "then": {
        "and": [
          "the response has a status of 406",
          " the response body has ErrorListReponse object",
          " error code is \"Header/UnsupportedVersion\""
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#http-headers"
        }
      ],
      "negative": false
    },
    "A.CVM.001": {
      "id": "A.CVM.001",
      "title": "Validate version - <x-v-min> is provided",
      "given": [
        "the <x-v-min> header is included in a get request"
      ],
      "when": [
        "the value for the <x-v-min>  is a positive integer"
      ],
      "then": {
        "and": [
          "<x-v> is in the repsonse header",
          "  <x-v> = [<x-v-min>, <x-v>]",
          " <x-v> is a positive integer"
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#http-headers"
        }
      ],
      "negative": false
    },
    "A.CVM.002": {
      "id": "A.CVM.002",
      "title": "Validate minimum version - validate <x-v-min> format",
      "given": [
        "the <x-v-min> header is included in a get request"
      ],
      "when": [
        "the <x-min-v> is a not a positive integer"
      ],
      "then": {
        "and": [
          "the response has a status of 400",
          " the response body has ErrorListReponse object",
          " error code is \"Field/Invalid\""
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#http-headers"
        }
      ],
      "negative": false
    },
    "A.CFI.001": {
      "id": "A.CFI.001",
      "title": "Validate FAPI Interation ID - included in request",
      "given": [
        "the <x-fapi-interaction-id> is included in the header of the request"
      ],
      "when": [
        "the <x-fapi-interaction-id> is in a valid format "
      ],
      "then": {
        "and": [
          "the response has a status of 200",
          " the Data Holder has returned the <x-fapi-interaction-id> from the request in the response header"
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#http-headers"
        }
      ],
      "negative": false
    },
    "A.CFI.003": {
      "id": "A.CFI.003",
      "title": "Validate FAPI Interation ID - invalid format",
      "given": [
        "the <x-fapi-interaction-id> is included in the GET request"
      ],
      "when": [
        "the <x-fapi-interaction-id> is not in a valid format "
      ],
      "then": {
        "and": [
          "the response has a status of 400",
          " the response body has ErrorListReponse object",
          " error code is \"Header/invalid\""
        ]
      },
      "references": [
        {
          "uri": "https://consumerdatastandardsaustralia.github.io/standards/#http-headers"
        }
      ],
      "negative": false
    },
    "A.CFA.001": {
